config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  resources :books do
  	resources :reviews
  end
  root 'books#index'

end

app/models/book.rb
class Book < ActiveRecord::Base
	belongs_to :user
	belongs_to :category
	has_many :reviews

	has_attached_file :book_img, :styles => { :book_index => "250x350>", :book_show => "325x475>" }, :default_url => "/images/:style/missing.png"
  	validates_attachment_content_type :book_img, :content_type => /\Aimage\/.*\Z/
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :books
end

app/models/collaborate.rb
class Collaborate < ActiveRecord::Base
end

app/models/review.rb
class Review < ActiveRecord::Base
	belongs_to :book
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :books
	has_many :reviews
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
	before_action :find_book, only: [:show, :edit, :update, :destroy]
	
	def index
		@books = Book.all.order("created_at DESC")

		# if params[:category].blank?
		# 	@books =Book.all.order("created_at DESC")
		# else
		# 	@category_id = Category.find(params[:category])
		# 	@books = Book.where(:category_id => @category_id).order("created_at DESC")
		# end
	end

	def show
	end

	def new
		@book = current_user.books.build
		@categories = Category.all.map{ |c| [c.name, c.id] }
	end

	def create
		@book = current_user.books.build(book_params)
		@book.category_id = params[:category_id]

		if @book.save
			redirect_to root_path
		else
			render 'new'
		end
	end

	def edit
		@categories = Category.all.map{ |c| [c.name, c.id] }
	end

	def update
		@book.category_id = params[:category_id]

		if @book.update(book_params)
			redirect_to book_path(@book)
		else
			render 'edit'
		end
	end

	def destroy
		@book.destroy
		redirect_to root_path
	end


	private

	def book_params
		params.require(:book).permit(:title, :description, :author, :category_id, :book_img)
	end

	def find_book
		@book = Book.find(params[:id])
	end
end

app/controllers/collaborates_controller.rb
class CollaboratesController < ApplicationController
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
	before_action :find_book
	before_action :find_review, only: [:edit, :update, :destroy]

	def new
		@review = Review.new
	end

	def create
		@review = Review.new(review_params)
		@review.book_id = @book.id
		@review.user_id = current_user.id

		if @review.save
			redirect_to book_path(@book)
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @review.update(review_params)
			redirect_to book_path(@book)
		else
			render 'edit'
		end
	end

	def destroy
		@review.destroy
		redirect_to book_path(@book)
	end

	private

		def review_params
			params.require(:review).permit(:rating, :comment)
		end

		def find_book
			@book = Book.find(params[:book_id])
		end

		def find_review
			@review = Review.find(params[:id])
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/collaborates_helper.rb
module CollaboratesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/books/_form.html.erb
<%= simple_form_for @book do |f| %>
	<%= f.file_field :book_img %>
	<%= select_tag(:category_id, options_for_select(@categories), :prompt => "Select Category") %>
	<%= f.input :title , label: "Book Title" %>
	<%= f.input :description %>
	<%= f.input :author %>
	<%= f.button :submit %>
<% end %>

app/views/books/edit.html.erb
<div class="container">

	<h1>Edit Book</h1>

	<%= simple_form_for @book, html: {multipart: true} do |f| %>
		<%= f.file_field :book_img %>
		<%= f.select :category_id, @categories %>
		<%= f.input :title , label: "Book Title" %>
		<%= f.input :description %>
		<%= f.input :author %>
		<%= f.button :submit %>
	<% end %>
</div>

app/views/books/index.html.erb
<div class="container">
<h1 class="current-category"><%= params[:category] %></h1>

	<div class="row">
		<div class="col s12 m8 l9">
			<% if @books.count == 0 %>
				<h3>There are no books in this category</h3>
			<% else %>
				<div class="row">
					<% @books.each do |book| %>
						<div class="col s12 m6 l4">
							<a href="/books/ <%= book.id %>">
								<%= image_tag book.book_img.url(:book_index), class: "book" %>
							</a>
						</div>
					<% end %>
				</div>
			<% end %>
		</div>
		<div class="col s12 m4 l3 z-depth-3 sidebar-offcanvas" id="sidebar" role="navigation">
		    <ul class="nav category-nav"> <h4>Categories</h4>
		        <li class="active"><a href="#">Programming</a></li>
		        <li><a href="#">Language</a></li>
		        <li><a href="#">Mathematics</a></li>
		        <li><a href="#">Electronics</a></li>              
		    </ul>

		    <div class="card sticky-action">
		    	<h5>Book of the Week</h5>
			    <div class="card-image waves-effect waves-block waves-light">
			      <img class="activator" src="http://localhost:3000/system/books/book_imgs/000/000/012/book_show/cover_359x475.jpg">
			    </div>
			    <div class="card-content">
			      <span class="card-title activator grey-text text-darken-4">More Info.<i class="material-icons right">more_vert</i></span>
			      <p><a href="#">This is a link</a></p>
			    </div>
			    <div class="card-reveal">
			      <span class="card-title grey-text text-darken-4"><i class="material-icons right">close</i></span>
			      <p>Advanced Java Game Programming teaches you how to create desktop and Internet computer games using the latest Java programming language techniques. Whereas other Java game programming books focus on introductory Java material, this book covers game programming for experienced Java developers.</p>
			      <a class="waves-effect waves-light btn">Get a Copy</a>
			    </div>
			</div>
		</div>
	</div>
</div>

app/views/books/new.html.erb
<div class="container">
	<h3>New Book</h3>

	<%= render 'form' %>
</div>

app/views/books/show.html.erb
<div class="row">
	<div class="col s12 m4 l3">
		<div class="card sticky-action">
		    <div class="card-image ">
		  	    <%= image_tag @book.book_img.url(:book_show), class: "book-show activator" %>
		    </div>
		    <div class="card-content">
		      	<p class="card-action"><a href="#" class="right"><%= link_to "Download", @book.book_img.url(:original, false) %></a></p>
		    </div>
	  	</div>





		<div class="links btn-group center-align">
			<% if user_signed_in? %>
				<% if @book.user_id == current_user.id %>
					<%= link_to "Edit", edit_book_path(@book), class: "btn btn-custom" %>
					<%= link_to "Delete", book_path(@book), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-custom" %>
				<% end %>
			<% end -%>
		</div>
	</div>

	<div class="col s12 m6 l9">
		<!-- <div class="book-info">
			<h2 class="book-title"><%= @book.title %></h2>
			<h3 class="book-author"><span>Author: </span> <%= @book.author %></h3>
			<h4 class="book-author"><%= @book.category.name %></h4>
			<p class="book-desc"><%= @book.description %></p>
		</div> -->

		<ul class="collapsible popout" data-collapsible="accordion">
		    <li>
		     	<div class="collapsible-header active"><i class="material-icons">description</i>Description</div>
		      	<div class="collapsible-body book-description">
		      		<h4><%= @book.title %></h4>
		      		<h5><%= @book.category.name %></h5>
		      		<p class="book-desc"><%= @book.description %></p>
		      	</div>
		    </li>
		    <li>
		      <div class="collapsible-header"><i class="material-icons">person_pin</i>About Author</div>
		      <div class="collapsible-body"><p><span>Author: </span> <%= @book.author %></p></div>
		    </li>
		    <li>
		      <div class="collapsible-header"><i class="material-icons">live_help</i>Need the Book?</div>
		      <div class="collapsible-body"><p>Contact Us..</p></div>
		    </li>
		    <li>
		      <div class="collapsible-header"><i class="material-icons">comment</i>Review</div>
		      <div class="collapsible-body">
		      		<div class="reviews">
						<h1> Reviews </h1>
						<%= render @book.reviews %>
						<a href="#!" class="waves-effect waves-green right-align"><%= link_to "Add Reviews", new_book_review_path(@book), class: "btn-large add-review-button" %></a>
					</div>
			   
			   		
		      </div>
		    </li>
		</ul>  
	</div>

	

	<div class="col s12 m12 l12">
		<h4 >Similar Books</h4>
	</div>

	<div class="similar-books">
		<div class="col s12 m6 l3">
			<div class="card sticky-action">
			    <div class="card-image waves-effect waves-block waves-light">
			  	    <%= image_tag @book.book_img.url(:book_show), class: "book-show activator" %>
			    </div>
			    <div class="card-content">
			   	   <span class="card-title activator grey-text text-darken-4"><%= @book.title %><i class="material-icons right">more_vert</i></span>
			      	<p class="card-action"><a href="#"><span>Author: </span> <%= @book.author %></a><a href="#" class="right">PDF</a></p>
			    </div>
			    <div class="card-reveal">
			    	  <span class="card-title grey-text text-darken-4"><%= @book.title %><i class="material-icons right">close</i></span>
			    	  <span class="card-title grey-text text-darken-4 blue-grey"><span>Author: </span> <%= @book.author %></span>
			   	   <p class="book-desc"><%= @book.description %></p>
			    </div>
		  	</div>
		</div>

		<div class="col s12 m6 l3">
			<div class="card sticky-action">
			    <div class="card-image waves-effect waves-block waves-light">
			  	    <%= image_tag @book.book_img.url(:book_show), class: "book-show activator" %>
			    </div>
			    <div class="card-content">
			   	   <span class="card-title activator grey-text text-darken-4"><%= @book.title %><i class="material-icons right">more_vert</i></span>
			      	<p class="card-action"><a href="#"><span>Author: </span> <%= @book.author %></a><a href="#" class="right">PDF</a></p>
			    </div>
			    <div class="card-reveal">
			    	  <span class="card-title grey-text text-darken-4"><%= @book.title %><i class="material-icons right">close</i></span>
			    	  <span class="card-title grey-text text-darken-4 blue-grey"><span>Author: </span> <%= @book.author %></span>
			   	   <p class="book-desc"><%= @book.description %></p>
			    </div>
		  	</div>
		</div>

		<div class="col s12 m6 l3">
			<div class="card sticky-action">
			    <div class="card-image waves-effect waves-block waves-light">
			  	    <%= image_tag @book.book_img.url(:book_show), class: "book-show activator" %>
			    </div>
			    <div class="card-content">
			   	   <span class="card-title activator grey-text text-darken-4"><%= @book.title %><i class="material-icons right">more_vert</i></span>
			      	<p class="card-action"><a href="#"><span>Author: </span> <%= @book.author %></a><a href="#" class="right">PDF</a></p>
			    </div>
			    <div class="card-reveal">
			    	  <span class="card-title grey-text text-darken-4"><%= @book.title %><i class="material-icons right">close</i></span>
			    	  <span class="card-title grey-text text-darken-4 blue-grey"><span>Author: </span> <%= @book.author %></span>
			   	   <p class="book-desc"><%= @book.description %></p>
			    </div>
		  	</div>
		</div>

		<div class="col s12 m6 l3">
			<div class="card sticky-action">
			    <div class="card-image waves-effect waves-block waves-light">
			  	    <%= image_tag @book.book_img.url(:book_show), class: "book-show activator" %>
			    </div>
			    <div class="card-content">
			   	   <span class="card-title activator grey-text text-darken-4"><%= @book.title %><i class="material-icons right">more_vert</i></span>
			      	<p class="card-action"><a href="#"><span>Author: </span> <%= @book.author %></a><a href="#" class="right">PDF</a></p>
			    </div>
			    <div class="card-reveal">
			    	  <span class="card-title grey-text text-darken-4"><%= @book.title %><i class="material-icons right">close</i></span>
			    	  <span class="card-title grey-text text-darken-4 blue-grey"><span>Author: </span> <%= @book.author %></span>
			   	   <p class="book-desc"><%= @book.description %></p>
			    </div>
		  	</div>
		</div>
	</div>
</div>



<script>
	$('.review-rating').raty({
		readOnly: true,
		score: function() {
			return $(this).attr('data-score');
		},
		path: '/assets/'
	});
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyBookStore</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
</head>
<body>
	<nav class="blue-grey">
	    <div class="nav-wrapper">
		    <a href="#!" class="brand-logo"><%= link_to "My BookStore", root_path, class: "navbar-brand" %></a>
		    <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>

		    <ul class="right hide-on-med-and-down">
		    	<li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Sort Book <span class="caret"></span></a>

					<ul class="dropdown-menu" role="menu">
						<% Category.all.each do |category| %>
							<li class="<%= 'active' if params[:category] == category.name %>">
								<%= link_to category.name, books_path(category: category.name), class: "link" %>
							</li>
						<% end %>
					</ul>
				</li>
				<% if user_signed_in? %>
					<li><%=link_to "Add Book", new_book_path %></li>
				<% end %>
		        <li><a href="#">Collaborate</a></li>
		        <li><a href="#">About Us</a></li>
		        <li><a href="#">Contact Us</a></li>
		        <li>
			        <form>
				        <div class="input-field">
				          <input id="search" type="search" required>
				          <label for="search"><i class="material-icons">search</i></label>
				          <i class="material-icons">close</i>
				        </div>
				    </form>
			      </li>
		        <% if user_signed_in? %>
					<li><%=link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
				<% else %>
					<li><%=link_to "Sign Up", new_user_registration_path %></li>
					<li><%=link_to "Sign In", new_user_session_path %></li>
				<% end %>
				<li><a class="waves-effect waves-light btn-large">Donate a Book</a></li>
		    </ul>
		    <ul class="side-nav" id="mobile-demo">
		        <li><a href="#">Home</a></li>
		        <li><a href="#">Collaborate</a></li>
		        <li><a href="#">About Us</a></li>
		        <li><a href="#">Contact Us</a></li>
		        <li><a class="waves-effect waves-light btn-large">Donate Now</a></li>
		    </ul>
	    </div>
	</nav>


	<p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

   		<div class="single-book">
		  	<%= yield %>
		</div>
    </div>
	
    <footer class="page-footer blue-grey darken-3">
          <div class="container">
            <div class="row">
              <div class="col l6 s12">
              	  <h5 class="white-text">My BookStore, The Gambia</h5>
              	  <p class="grey-text text-lighten-4"><strong>E-mail:</strong><a href="mailto:info@mybookstore.gm">info@mybookstore.gm</a></p>
              	  <p class="grey-text text-lighten-4"><strong>Tel:</strong><a href="tel"> +220 742 7992</a></p>
              	  <p class="grey-text text-lighten-4">Help make education accessible and affordable to all.</p>
              	  <ul>
              	  	<li><a class="waves-effect waves-light btn-large">Donate Now</a></li>
              	  </ul>
              </div>
	            <div class="col l4 offset-l2 s12">
	            	<h5 class="white-text">Links</h5>
	             	<ul>
	             	    <li><a class="grey-text text-lighten-3" href="#!">Collaborate</a></li>
	             	    <li><a class="grey-text text-lighten-3" href="#!">About Us</a></li>
	              	    <li><a class="grey-text text-lighten-3" href="#!">Contact Us</a></li>
	               		<li><a class="grey-text text-lighten-3" href="#!">Donors</a></li>
	                </ul>
	            </div>
            </div>
          </div>
          <div class="footer-copyright blue-grey darken-4">
            <div class="container">
            	&copy; 2016 My Book Store, The Gambia.
            <a class="grey-text text-lighten-4 right" href="#!">More Links</a>
            </div>
          </div>
    </footer>
</body>
</html>

app/views/reviews/_form.html.erb
<%= simple_form_for([@book, @book.reviews.build]) do |f| %>
	<div id="rating-form">
		<label> Rating </label>
	</div>
	<%= f.input :comment %>
	<%= f.button :submit, :class => "btn-custom2" %>
<% end %>

<script>
	$('#rating-form').raty({
		path: '/assets/',
		scoreName: 'review[rating]' 
	});
</script>

app/views/reviews/_review.html.erb
<div class="review">
	<div class="review-rating" data-score="<%= review.rating %>"></div>
	<p class="review-comment"><%= review.comment %></p>
	
	<% if user_signed_in? %>
		<% if review.user_id == current_user.id %>
			<div class="links btn-group">
				<%= link_to "Edit", edit_book_review_path(review.book, review), class: "btn btn-custom" %>
				<%= link_to "Delete", book_review_path(review.book, review), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-custom" %>
			</div>
		<% end %>
	<% end %>
</div>

app/views/reviews/edit.html.erb
<div class="col-md-10 col-md-offset-1">
	<div class="edit-review-form">
	<h1> Edit Review </h1>
		<%= simple_form_for([@book, @review]) do |f| %>
			<div id="rating-form">
				<label> Rating </label>
			</div>
			<%= f.input :comment %>
			<%= f.button :submit, :class => "btn-custom2" %>
		<% end %>
	</div>
</div>

<script>
	$('#rating-form').raty({
		path: '/assets/',
		scoreName: 'review[rating'
	});
</script>

app/views/reviews/new.html.erb
<div class="col-md-10 col-md-offset-1">
	<div class="new-review-form">
		<h1> Post Review </h1>
		<%= render 'form' %>
	</div>
</div>